name: Nightly

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  schedule:
    - cron: '0 0 12 * * ? *' # at 12:00:00pm every day

jobs:
  check_latest_commit_date:
    runs-on: ubuntu-latest

    name: Check Latest Commit

    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}

    steps:
      - uses: actions/checkout@v2
      - name: Print the Latest Commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: Check Latest Commit
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "::set-output name=should_run::false"

  test:
    runs-on: self-hosted
    timeout-minutes: 1200

    needs: check_latest_commit_date
    if: ${{ needs.check_latest_commit_date.outputs.should_run != 'false' }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install NPM Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:nightly
