name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-v2:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: packages/v2

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install NPM Dependencies
        run: yarn install

      - name: Build
        run: yarn build

  test:
    needs: build-v2
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: packages/v3

      - name: Install NPM Dependencies
        run: yarn install

      # temporary remove lint check from CI since solhint doesn't fully support Solidity 0.8.9
      # - name: Lint
      #   run: yarn lint

      - name: Test
        run: CI=1 yarn test

      - name: Test Migration
        run: CI=1 yarn test-migration
