name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 600

    defaults:
      run:
        shell: bash
        working-directory: packages/v3

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install V2 NPM Dependencies
        run: yarn install
        working-directory: packages/v2

      - name: Build V2
        run: yarn build
        working-directory: packages/v2

      - name: Install NPM Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci
